### ISSUE TITLE
email-on-status-change.js

### ISSUE THREAD

**Issue by Okimomale** [bradymholt/vistaicm-server#1]
The following hook will send 'armed' and 'unarmed' notifications when I arm or disarm my Vista 20P in stay or instant modes, but when I arm the system in "away" mode, I do not get any arming notification.

Here is the email-on-status-change.js hook that I am using.

var nodemailer = require('nodemailer');
var smtpTransport = nodemailer.createTransport("SMTP",{
    service: "Gmail",
    auth: {
        user: "xxxxxxx@gmail.com",
        pass: "xxxxxxxxxxx"
    }
});
module.exports = function (ICM) {
    ICM.events.on('armStatusChanged', function(armStatus){
       if (armStatus == 0 || armStatus == 1) {
            var mailOptions = {
                 from: 'Winding Way Status Change xxxxxx@gmail.com', // sender address
                to: 'xxxxxx@gmail.com', // list of receivers
                subject: armStatus == 1 ? '**\* System Armed **_' : '**_ System Disarmed ***',
                text: ICM.getAlarmStatusDetail(false), // plaintext body
                html: ICM.getAlarmStatusDetail(true) // html body
            };
            smtpTransport.sendMail(mailOptions, function(error, response){
                console.log(error ? error : "Email sent: " + response.message);
            });
        }
    });
};

Any ideas on why notifications do not go out when the system is armed in 'away' mode ?

**Comment by bradymholt** [comment]
That's strange.  Have you tried running it on a terminal and looking at the logging?  I am curious if the ARMED event is firing when you arm in AWAY mode.  If it is, it should show it on the console.  If not, something else might be going.

**Comment by Okimomale** [comment]
Looking at it in the console shows that when it arms in 'stay' mode, it gives a "Arm Status: 1", and then generates the email.  When I arm it 'away' mode, it returns "Arm Status:2", and no email is generated.
So How can I change the hook so it will generate the email on BOTH an Arm Status:1 & Arm Status:2 ?

**Comment by Okimomale** [comment]
Brady .....
Is there any chance you can could post the syntax change in the 'email-on-status-change.js' hook that needs to be made to make the "arm status:2" generate an email like the "arm status:1" does  ?  
Any help would be appreciated.  Thanks.

**Comment by bradymholt** [comment]
This should work for you.  The changes are in bold.

<pre>
var nodemailer = require('nodemailer');
var smtpTransport = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: {
        user: "xxxxxxx@gmail.com",
        pass: "xxxxxxxxxxx"
    }
});
module.exports = function(ICM) {
    ICM.events.on('armStatusChanged', function(armStatus) {
        <strong>if ([0,1,2].indexOf(armStatus) > -1) {</strong>
            var mailOptions = {
                from: 'Winding Way Status Change xxxxxx@gmail.com', // sender address
                to: 'xxxxxx@gmail.com', // list of receivers
                <strong>subject: [1,2].indexOf(armStatus) > -1 ? '*** System Armed ' : ' System Disarmed ***',</strong>
                text: ICM.getAlarmStatusDetail(false), // plaintext body
                html: ICM.getAlarmStatusDetail(true) // html body
            };
            smtpTransport.sendMail(mailOptions, function(error, response) {
                console.log(error ? error : "Email sent: " + response.message);
            });
        }
    });
};
</pre>
